using OrchestratorIDE.Core;

namespace OrchestratorIDE.Trust;

/// <summary>
/// Auto-discovers and loads .agent.md / AGENT.md / .clinerules from the project root.
/// The content is injected into the system prompt so the agent always knows project conventions.
/// </summary>
public class RulesLoader
{
    private static readonly string[] _candidates =
    [
        ".agent.md", "AGENT.md", ".clinerules", "CLAUDE.md", ".rules.md"
    ];

    /// <summary>
    /// Loads and composes rules for the current agent run:
    ///   1. Global agent file (~AppData/OrchestratorIDE/global_agent.md) — always applied
    ///   2. Workspace-specific file (.agent.md / AGENT.md / …)           — overrides / extends global
    /// Returns the merged text, or empty string if neither file exists.
    /// </summary>
    public async Task<string> LoadAsync(string workspaceRoot)
    {
        var parts = new System.Text.StringBuilder();

        // ── 1. Global agent ──────────────────────────────────────────────────
        var globalPath = Core.AgentPresets.GlobalAgentPath;
        if (File.Exists(globalPath))
        {
            try
            {
                var globalContent = await File.ReadAllTextAsync(globalPath);
                if (!string.IsNullOrWhiteSpace(globalContent))
                    parts.AppendLine($"[Global agent rules]\n{globalContent.Trim()}");
            }
            catch { /* skip unreadable */ }
        }

        // ── 2. Workspace rules ───────────────────────────────────────────────
        if (!string.IsNullOrEmpty(workspaceRoot))
        {
            foreach (var name in _candidates)
            {
                var path = Path.Combine(workspaceRoot, name);
                if (File.Exists(path))
                {
                    try
                    {
                        var content = await File.ReadAllTextAsync(path);
                        if (!string.IsNullOrWhiteSpace(content))
                            parts.AppendLine($"[Workspace rules from {name}]\n{content.Trim()}");
                    }
                    catch { /* skip unreadable */ }
                    break; // first match wins
                }
            }
        }

        return parts.ToString().Trim();
    }

    public string? FindRulesFile(string workspaceRoot)
    {
        foreach (var name in _candidates)
        {
            var path = Path.Combine(workspaceRoot, name);
            if (File.Exists(path)) return path;
        }
        return null;
    }

    public static string DefaultTemplate(string projectName) => $"""
        # Agent Rules — {projectName}
        # Generated by OrchestratorIDE — edit freely to match your project

        ---

        ## Project Context
        *(fill in — the agent reads this on every run)*

        ```
        Project     : {projectName}
        Language    : [C# / Python / TypeScript / …]
        Build cmd   : [dotnet build / pytest / npm run build / …]
        Test cmd    : [dotnet test / pytest tests/ / npm test / …]
        Lint cmd    : [dotnet format / ruff check . / eslint . / …]
        Entry point : [src/Main.cs / app.py / index.ts / …]
        Key deps    : [list the unusual ones]
        ```

        ---

        ## Core Operating Principles
        *(these mirror Claude Code's documented agent behavior contract)*

        ### 1 — Minimal Footprint
        - Only modify files that are directly relevant to the task asked
        - Do not refactor, rename, or "clean up" things not mentioned in the request
        - Do not add dependencies, configs, or boilerplate that weren't requested
        - Scope creep is a bug, not a feature

        ### 2 — Read Before Writing
        - Before editing any file: read the relevant section first
        - Before creating a file: check whether one already exists that does the job
        - Search the codebase before assuming something doesn't exist
        - Understand the full call chain before modifying any node in it

        ### 3 — Prefer Reversible Over Irreversible
        - Soft deletes before hard deletes
        - Flags / feature gates before removing capabilities
        - Commits checkpoint state before large changes
        - When an action cannot be undone, state that clearly and wait for confirmation

        ### 4 — Small, Targeted Changes
        - Surgical edits over full rewrites — change only the lines that must change
        - One logical unit of work per tool call
        - If a change touches more than 3 files, pause and explain why before continuing

        ### 5 — Verify Before Declaring Done
        - Run the build. 0 errors required. Warnings are acceptable if pre-existing.
        - Run the relevant test(s) after any behaviour change
        - If the build command is unknown, ask — don't skip verification
        - Do not say "this should work" — confirm that it does

        ### 6 — Honesty Over Sycophancy
        - If a request is ambiguous, ask for clarification — do not guess and present it as fact
        - If you are uncertain about a root cause, say so
        - If a proposed approach has a real downside, name it before proceeding
        - Never fabricate file paths, API names, or library behaviour

        ### 7 — Correct Action Hierarchy
        When deciding what to do, apply this order:
        ```
        1. Is there explicit instruction in this file?   → follow it exactly
        2. Is there an established pattern in the repo?  → follow that pattern
        3. Is the task unambiguous?                      → do it; report what you did
        4. Is the task ambiguous but low-risk?           → pick the obvious path; flag your choice
        5. Is the task ambiguous AND high-risk?          → stop and ask before acting
        ```

        ### 8 — Communication Contract
        - State what you are about to do *before* using a tool, not after
        - After completing a task: what changed, why, and what to verify
        - Flag blockers immediately — do not silently work around them
        - Be concise when acting; be thorough when planning
        - Do not pad responses with affirmations ("Great question!", "Certainly!")

        ### 9 — Tool Use Discipline
        - Use `grep_code` / `get_outline` before assuming structure
        - Use `read_file` on the exact section needed, not the whole file when a range suffices
        - Never call a tool that doesn't exist — if missing, say what you need
        - Chain tool calls efficiently: read → edit → verify in one pass when possible

        ### 10 — Git & Commits
        - Commit only when explicitly asked or when a milestone is clearly complete
        - Commit message format: `type: short imperative summary` (feat/fix/refactor/docs/test/chore)
        - Every commit must build cleanly
        - Never amend a commit that has already been shared — create a new one

        ---

        ## Project-Specific Rules
        *(fill in — override or extend the principles above for this project)*

        ```
        Code style  : [tabs vs spaces, naming conventions, file organization]
        Testing     : [what test framework, where tests live, coverage expectations]
        Avoid       : [patterns, libs, approaches that are banned in this repo]
        Before PR   : [linting, test suite, specific manual checks]
        ```

        ---

        ## Dangerous Paths / Files
        *(list anything the agent should never touch without explicit confirmation)*

        ```
        # Example:
        # - Production .env files
        # - Database migration scripts (require manual review)
        # - Auth/crypto code (changes need a second pair of eyes)
        ```

        ---

        *Drop specific tool commands, architecture notes, and "gotchas" below this line.*
        *The agent reads everything in this file on every run — keep it accurate.*
        """;

}
