// Copyright (C) 2025-present hardcoreerik / TheOrc contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Phase 5B Stage 2B test: compares TokenizerProfile::encode() against the
// oracle-derived fixtures generated by
// Tools/OrcEnginePhase5B/tools/generate_pretok_tables.py (real
// tokenizers==0.22.2, pinned smollm2-135m/tokenizer.json). Requires a real
// GGUF path (the same canonical explicit artifact Stage 1 uses) since
// TokenizerProfile can only be constructed from real or synthetic GGUF
// metadata -- there is no independent construction path for Stage 2B.
#include <array>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

#include "orcengine/pretokenize.hpp"
#include "orcengine/tokenizer.hpp"
#include "byte_alphabet_oracle.hpp"
#include "encode_oracle_fixtures.hpp"
#include "pretok_invalid_utf8.hpp"

using namespace orcengine;

namespace {
int g_failures = 0;
void check(bool cond, const std::string& name) {
    std::printf("[%s] %s\n", cond ? "PASS" : "FAIL", name.c_str());
    if (!cond) ++g_failures;
}

// GPT-2's closed-form byte_encoder, reconstructed independently HERE from
// the published algorithm -- NOT by calling into tokenizer.cpp's own
// kByteToCodepoint (that table is private to tokenizer.cpp's anonymous
// namespace and is not reachable from this test binary at all). What this
// check actually proves: an independent reconstruction of the closed-form
// algorithm matches the oracle-generated table (kOracleByteToCodepoint,
// built from tokenizers==0.22.2 in generate_pretok_tables.py) at all 256
// entries. It does NOT execute or directly compare tokenizer.cpp's own
// production array; that array uses the identical published construction
// (same source values, verified by inspection when written) but is not
// itself invoked by this test. Widening the public API to expose it purely
// for this comparison was judged unnecessary architecture for what the
// closed-form algorithm's determinism already gives high confidence in.
uint32_t reference_byte_to_codepoint(unsigned int byte) {
    static const auto table = [] {
        std::array<uint32_t, 256> t{};
        std::vector<unsigned int> printable;
        for (unsigned int b = 0x21; b <= 0x7E; ++b) printable.push_back(b);
        for (unsigned int b = 0xA1; b <= 0xAC; ++b) printable.push_back(b);
        for (unsigned int b = 0xAE; b <= 0xFF; ++b) printable.push_back(b);
        std::array<bool, 256> is_printable{};
        for (unsigned int b : printable) is_printable[b] = true;
        for (unsigned int b : printable) t[b] = b;
        uint32_t n = 0;
        for (unsigned int b = 0; b < 256; ++b) {
            if (!is_printable[b]) {
                t[b] = 256 + n;
                ++n;
            }
        }
        return t;
    }();
    return table[byte];
}
}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <canonical-explicit-gguf-path>\n", argv[0]);
        return 2;
    }

    try {
        std::printf("=== Phase 5B Stage 2B: independent byte-alphabet reconstruction vs. oracle table ===\n");
        int byte_mismatches = 0;
        for (int b = 0; b < 256; ++b) {
            const uint32_t expected = pretok_fixtures::kOracleByteToCodepoint[b];
            const uint32_t got = reference_byte_to_codepoint(static_cast<unsigned int>(b));
            if (expected != got) ++byte_mismatches;
        }
        check(byte_mismatches == 0,
              "all 256 independently-reconstructed entries agree with the oracle-generated table "
              "(does not directly execute tokenizer.cpp's own production table)");

        std::printf("\n=== Loading canonical explicit tokenizer profile ===\n");
        const TokenizerProfile profile = load_tokenizer_profile(argv[1]);
        check(profile.vocab_size() == 49152, "profile loads with vocab_size == 49152");

        std::printf("\n=== Encode oracle fixture comparison ===\n");
        std::size_t exact_pass = 0;
        for (std::size_t i = 0; i < pretok_fixtures::kEncodeFixtureCount; ++i) {
            const auto& fx = pretok_fixtures::kEncodeFixtures[i];
            const SpecialTokenMode mode =
                fx.mode == 'A' ? SpecialTokenMode::LiteralText : SpecialTokenMode::RecognizeControlTokens;

            std::vector<int64_t> got;
            bool threw = false;
            try {
                got = profile.encode(fx.utf8, mode);
            } catch (const std::exception& ex) {
                threw = true;
                check(false, std::string("fixture '") + fx.id + "' -- unexpected throw: " + ex.what());
            }
            if (threw) continue;

            bool same_count = got.size() == fx.id_count;
            check(same_count, std::string("fixture '") + fx.id + "' -- id count (" +
                                   std::to_string(got.size()) + " vs oracle " + std::to_string(fx.id_count) + ")");
            bool same_ids = same_count;
            if (same_count) {
                for (std::size_t k = 0; k < fx.id_count; ++k) {
                    if (got[k] != fx.ids[k]) {
                        same_ids = false;
                        break;
                    }
                }
            }
            check(same_ids, std::string("fixture '") + fx.id + "' -- exact token IDs match oracle");
            if (same_ids) ++exact_pass;

            // Determinism: repeat and require identical result.
            const std::vector<int64_t> got2 = profile.encode(fx.utf8, mode);
            check(got == got2, std::string("fixture '") + fx.id + "' -- deterministic repeat invocation");
        }
        std::printf("[INFO] encode oracle fixtures: %zu/%zu exact-match\n", exact_pass,
                    pretok_fixtures::kEncodeFixtureCount);

        // --- Structural checks not covered by the fixture corpus ----------
        std::printf("\n=== Structural checks ===\n");
        check(profile.encode("").empty(), "empty input returns empty ID vector (LiteralText)");
        check(profile.encode("", SpecialTokenMode::RecognizeControlTokens).empty(),
              "empty input returns empty ID vector (RecognizeControlTokens)");
        check(SpecialTokenMode{} == SpecialTokenMode::LiteralText, "LiteralText is the default enum value");

        {
            // Default-argument call must equal an explicit LiteralText call.
            const std::string_view text = "Hello, world!";
            check(profile.encode(text) == profile.encode(text, SpecialTokenMode::LiteralText),
                  "default mode argument is LiteralText");
        }

        {
            // Embedded NUL must survive through Mode A end-to-end (not just
            // pretokenization) -- the byte at the NUL position must be
            // present in the mapped/BPE'd stream, so a NUL-containing input
            // must not throw and must not silently truncate before the
            // trailing text's tokens are produced.
            std::string s = "before";
            s.push_back('\0');
            s += "after";
            std::vector<int64_t> nul_ids;
            bool threw = false;
            try {
                nul_ids = profile.encode(s);
            } catch (const std::exception&) {
                threw = true;
            }
            check(!threw, "embedded NUL does not throw during encode");
            check(!nul_ids.empty(), "embedded NUL input produces a non-empty ID vector");
        }

        {
            // Invalid UTF-8 must reject the ENTIRE operation -- no partial
            // ID vector -- with EXACTLY PretokenizeError (the input-dependent
            // UTF-8 boundary), for both modes. EncodingError (or any other
            // exception type) is a FAILURE here: it would mean invalid input
            // is being misreported as an internal encoding-invariant
            // violation rather than the input problem it actually is.
            for (std::size_t i = 0; i < pretok_fixtures::kInvalidUtf8CaseCount; ++i) {
                const auto& c = pretok_fixtures::kInvalidUtf8Cases[i];
                for (SpecialTokenMode mode :
                     {SpecialTokenMode::LiteralText, SpecialTokenMode::RecognizeControlTokens}) {
                    bool threw = false;
                    bool right_type = false;
                    try {
                        std::vector<int64_t> ids = profile.encode(c.bytes, mode);
                        (void)ids;
                    } catch (const PretokenizeError&) {
                        threw = true;
                        right_type = true;
                    } catch (const std::exception&) {
                        threw = true;
                        right_type = false;
                    }
                    const std::string mode_label = mode == SpecialTokenMode::LiteralText ? "A" : "B";
                    check(threw, std::string("invalid UTF-8 '") + c.id + "' throws (mode=" + mode_label + ")");
                    check(right_type, std::string("invalid UTF-8 '") + c.id +
                                           "' throws exactly PretokenizeError, not EncodingError or any other "
                                           "type (mode=" +
                                           mode_label + ")");
                }
            }
        }

        std::printf("\n=== Summary ===\n");
        if (g_failures == 0) {
            std::printf("ALL CHECKS PASSED\n");
            return 0;
        }
        std::printf("%d FAILURES\n", g_failures);
        return 1;
    } catch (const std::exception& ex) {
        std::fprintf(stderr, "[FAIL] unexpected exception: %s\n", ex.what());
        return 1;
    }
}
