// Copyright (C) 2025-present hardcoreerik / TheOrc contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Phase 5B Stage 2A test: compares orcengine::pretokenize() against the
// oracle-derived boundary fixtures generated by
// Tools/OrcEnginePhase5B/tools/generate_pretok_tables.py (real
// tokenizers==0.22.2, pinned smollm2-135m/tokenizer.json). Exercises
// pretokenization boundaries ONLY -- no byte-to-Unicode mapping, no BPE
// merges, no token IDs, no decoding; those remain unimplemented.
#include <cstdio>
#include <string>

#include "orcengine/pretokenize.hpp"
#include "pretok_invalid_utf8.hpp"
#include "pretok_oracle_fixtures.hpp"

using namespace orcengine;

namespace {
int g_failures = 0;
void check(bool cond, const std::string& name) {
    std::printf("[%s] %s\n", cond ? "PASS" : "FAIL", name.c_str());
    if (!cond) ++g_failures;
}

bool spans_equal(const std::vector<PretokenSpan>& a, const std::vector<PretokenSpan>& b) {
    if (a.size() != b.size()) return false;
    for (std::size_t k = 0; k < a.size(); ++k) {
        if (a[k].begin != b[k].begin || a[k].end != b[k].end) return false;
    }
    return true;
}
}  // namespace

int main() {
    std::printf("=== Phase 5B Stage 2A: pretokenization boundary proof ===\n");

    // --- Oracle differential comparison ------------------------------------
    std::size_t oracle_pass = 0;
    for (std::size_t i = 0; i < pretok_fixtures::kFixtureCount; ++i) {
        const auto& fx = pretok_fixtures::kFixtures[i];
        std::vector<PretokenSpan> got;
        bool threw = false;
        try {
            got = pretokenize(fx.utf8);
        } catch (const std::exception& ex) {
            threw = true;
            check(false, std::string("fixture '") + fx.id + "' -- unexpected throw: " + ex.what());
        }
        if (threw) continue;

        bool same_count = got.size() == fx.span_count;
        check(same_count, std::string("fixture '") + fx.id + "' -- span count (" +
                               std::to_string(got.size()) + " vs oracle " + std::to_string(fx.span_count) + ")");
        bool same_spans = same_count;
        if (same_count) {
            for (std::size_t k = 0; k < fx.span_count; ++k) {
                if (got[k].begin != fx.spans[k].begin || got[k].end != fx.spans[k].end) {
                    same_spans = false;
                    break;
                }
            }
        }
        check(same_spans, std::string("fixture '") + fx.id + "' -- exact byte boundaries match oracle");
        if (same_spans) ++oracle_pass;

        // Determinism: repeat the call and require byte-identical results.
        std::vector<PretokenSpan> got2 = pretokenize(fx.utf8);
        check(spans_equal(got, got2), std::string("fixture '") + fx.id + "' -- deterministic repeat invocation");
    }
    std::printf("[INFO] oracle fixtures: %zu/%zu exact-match\n", oracle_pass, pretok_fixtures::kFixtureCount);

    // --- Invalid UTF-8 must throw PretokenizeError, never partial output --
    for (std::size_t i = 0; i < pretok_fixtures::kInvalidUtf8CaseCount; ++i) {
        const auto& c = pretok_fixtures::kInvalidUtf8Cases[i];
        bool threw = false;
        bool right_type = false;
        try {
            std::vector<PretokenSpan> spans = pretokenize(c.bytes);
            (void)spans;
        } catch (const PretokenizeError&) {
            threw = true;
            right_type = true;
        } catch (const std::exception&) {
            threw = true;
            right_type = false;
        }
        check(threw, std::string("invalid UTF-8 '") + c.id + "' -- throws");
        check(right_type, std::string("invalid UTF-8 '") + c.id + "' -- throws exactly PretokenizeError");
    }

    // --- Structural / non-oracle checks -------------------------------------
    check(pretokenize("").empty(), "empty input returns empty span list");
    {
        // Embedded NUL: must not truncate the scan. "before\0after" (12 bytes).
        std::string s = "before";
        s.push_back('\0');
        s += "after";
        check(s.size() == 12, "embedded-NUL test string is exactly 12 bytes (sanity)");
        std::vector<PretokenSpan> spans = pretokenize(s);
        std::size_t last_end = spans.empty() ? 0 : spans.back().end;
        check(last_end == 12, "embedded NUL: scan reaches the full 12-byte input, not truncated at the NUL");
    }
    {
        // Repeat-encoding determinism beyond the fixture loop above: run a
        // representative string 5 times and require byte-identical spans.
        const std::string_view text = "The quick brown fox jumps over 42 lazy dogs.";
        std::vector<PretokenSpan> first = pretokenize(text);
        bool all_same = true;
        for (int i = 0; i < 5; ++i) {
            if (!spans_equal(pretokenize(text), first)) {
                all_same = false;
                break;
            }
        }
        check(all_same, "repeated encoding (5x) of a representative string is fully deterministic");
    }

    std::printf("\n=== Summary ===\n");
    if (g_failures == 0) {
        std::printf("ALL CHECKS PASSED\n");
        return 0;
    }
    std::printf("%d FAILURES\n", g_failures);
    return 1;
}
