// Copyright (C) 2025-present hardcoreerik / TheOrc contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace OrchestratorIDE.Services.Models;

/// <summary>
/// Runs lightweight capability tests against a local Ollama model
/// to measure write_file JSON generation reliability at different payload sizes.
///
/// Tests:
///   FileWriteSmall  — write_file hello.txt with 1 line  (~20 chars)
///   FileWriteMedium — write_file script.py with ~50 lines (~1.5 KB)
///   FileWriteLarge  — write_file app.py with ~150 lines  (~5 KB)
///
/// Results are saved to %APPDATA%\OrchestratorIDE\model-wiki\results.jsonl.
///
/// Does NOT use AgentLoop — makes direct /v1/chat/completions requests with
/// stream:false so results are self-contained and don't affect agent state.
///
/// Does NOT write to the user's active project workspace.
/// Uses %TEMP%\TheOrc\ModelTests\{timestamp}\ as an isolated temp workspace.
/// </summary>
public static class ModelCapabilityTestService
{
    private static readonly HttpClient _http = new() { Timeout = TimeSpan.FromSeconds(120) };

    // ── Test definitions ──────────────────────────────────────────────────────

    public static readonly string TestIdSmall  = "FileWriteSmall";
    public static readonly string TestIdMedium = "FileWriteMedium";
    public static readonly string TestIdLarge  = "FileWriteLarge";

    /// <summary>Prompt and expected content for each test level.</summary>
    private record TestDefinition(
        string TestId,
        string TestName,
        string PromptText,
        string ExpectedFileName,
        string ExpectedContent   // the model is asked to write exactly this
    );

    private static readonly TestDefinition SmallTest = new(
        TestIdSmall,
        "FileWrite Small (1-line text)",
        "Use write_file to create a file called 'hello.txt' with exactly this content:\nHello, World! This is a TheOrc capability test.\n\nWrite the file now.",
        "hello.txt",
        "Hello, World! This is a TheOrc capability test."
    );

    private static readonly string MediumContent = string.Join("\n",
        "# script.py — generated by TheOrc capability test",
        "# This is a ~50-line Python script to test write_file JSON reliability.",
        "",
        "import os",
        "import sys",
        "import json",
        "import time",
        "from datetime import datetime",
        "",
        "# Constants",
        "VERSION = '1.0.0'",
        "DEFAULT_TIMEOUT = 30",
        "MAX_RETRIES = 3",
        "",
        "def greet(name: str) -> str:",
        "    \"\"\"Return a greeting string.\"\"\"",
        "    return f'Hello, {name}! Welcome to TheOrc capability test.'",
        "",
        "def retry(func, retries: int = MAX_RETRIES):",
        "    \"\"\"Retry a function up to N times.\"\"\"",
        "    for attempt in range(retries):",
        "        try:",
        "            return func()",
        "        except Exception as e:",
        "            if attempt == retries - 1:",
        "                raise",
        "            time.sleep(1)",
        "",
        "def load_config(path: str) -> dict:",
        "    \"\"\"Load a JSON config file.\"\"\"",
        "    with open(path) as f:",
        "        return json.load(f)",
        "",
        "def save_result(data: dict, path: str) -> None:",
        "    \"\"\"Save results to a JSON file.\"\"\"",
        "    with open(path, 'w') as f:",
        "        json.dump(data, f, indent=2)",
        "",
        "def list_files(directory: str) -> list:",
        "    \"\"\"List all files in a directory.\"\"\"",
        "    return [",
        "        os.path.join(directory, f)",
        "        for f in os.listdir(directory)",
        "        if os.path.isfile(os.path.join(directory, f))",
        "    ]",
        "",
        "def main():",
        "    print(greet('user'))",
        "    print(f'Version: {VERSION}')",
        "    print(f'Timestamp: {datetime.now().isoformat()}')",
        "    print(f'Args: {sys.argv[1:]}')",
        "    return 0",
        "",
        "if __name__ == '__main__':",
        "    sys.exit(main())"
    );

    private static readonly TestDefinition MediumTest = new(
        TestIdMedium,
        "FileWrite Medium (~50-line script)",
        $"Use write_file to create a file called 'script.py' with exactly this content:\n\n{MediumContent}\n\nWrite the file now.",
        "script.py",
        MediumContent
    );

    private static readonly string LargeContent = string.Join("\n", Enumerable.Concat(
        new[]
        {
            "# app.py — generated by TheOrc capability test",
            "# This is a ~150-line Python app to test write_file JSON reliability.",
            "",
            "import os, sys, json, time, threading",
            "from datetime import datetime",
            "from pathlib import Path",
            "from typing import Optional, List, Dict, Any",
            "",
            "# ── Configuration ────────────────────────────────────────────",
            "",
            "APP_NAME    = 'CapabilityTestApp'",
            "VERSION     = '1.0.0'",
            "DEFAULT_HOST = 'localhost'",
            "DEFAULT_PORT = 8080",
            "",
            "# ── Models ───────────────────────────────────────────────────",
            "",
            "class Config:",
            "    def __init__(self, host: str = DEFAULT_HOST, port: int = DEFAULT_PORT):",
            "        self.host = host",
            "        self.port = port",
            "        self.debug = False",
            "        self.log_level = 'INFO'",
            "",
            "    def to_dict(self) -> Dict[str, Any]:",
            "        return {'host': self.host, 'port': self.port,",
            "                'debug': self.debug, 'log_level': self.log_level}",
            "",
            "    @classmethod",
            "    def from_dict(cls, d: Dict[str, Any]) -> 'Config':",
            "        c = cls(d.get('host', DEFAULT_HOST), d.get('port', DEFAULT_PORT))",
            "        c.debug = d.get('debug', False)",
            "        c.log_level = d.get('log_level', 'INFO')",
            "        return c",
            "",
            "    @classmethod",
            "    def from_file(cls, path: str) -> 'Config':",
            "        with open(path) as f:",
            "            return cls.from_dict(json.load(f))",
            "",
            "class Result:",
            "    def __init__(self, success: bool, data: Any = None, error: str = ''):",
            "        self.success = success",
            "        self.data    = data",
            "        self.error   = error",
            "        self.timestamp = datetime.now().isoformat()",
            "",
            "    def to_dict(self) -> dict:",
            "        return {'success': self.success, 'data': self.data,",
            "                'error': self.error, 'timestamp': self.timestamp}",
            "",
            "# ── Services ─────────────────────────────────────────────────",
            "",
            "class FileService:",
            "    def __init__(self, base_path: str):",
            "        self.base = Path(base_path)",
            "        self.base.mkdir(parents=True, exist_ok=True)",
            "",
            "    def read(self, name: str) -> Optional[str]:",
            "        try:",
            "            return (self.base / name).read_text(encoding='utf-8')",
            "        except FileNotFoundError:",
            "            return None",
            "",
            "    def write(self, name: str, content: str) -> None:",
            "        (self.base / name).write_text(content, encoding='utf-8')",
            "",
            "    def delete(self, name: str) -> bool:",
            "        p = self.base / name",
            "        if p.exists():",
            "            p.unlink()",
            "            return True",
            "        return False",
            "",
            "    def list_all(self) -> List[str]:",
            "        return [p.name for p in self.base.iterdir() if p.is_file()]",
            "",
            "class LogService:",
            "    def __init__(self, level: str = 'INFO'):",
            "        self.level = level",
            "        self._lock = threading.Lock()",
            "",
            "    def log(self, msg: str, level: str = 'INFO') -> None:",
            "        with self._lock:",
            "            ts = datetime.now().strftime('%H:%M:%S')",
            "            print(f'[{ts}] [{level}] {msg}')",
            "",
            "    def info(self, msg: str)  -> None: self.log(msg, 'INFO')",
            "    def warn(self, msg: str)  -> None: self.log(msg, 'WARN')",
            "    def error(self, msg: str) -> None: self.log(msg, 'ERROR')",
            "",
            "# ── Main application ─────────────────────────────────────────",
            "",
            "class App:",
            "    def __init__(self, config: Config):",
            "        self.config  = config",
            "        self.files   = FileService(os.getcwd())",
            "        self.log     = LogService(config.log_level)",
            "        self._running = False",
            "",
            "    def start(self) -> None:",
            "        self._running = True",
            "        self.log.info(f'Starting {APP_NAME} v{VERSION}')",
            "        self.log.info(f'Host: {self.config.host}:{self.config.port}')",
            "",
            "    def stop(self) -> None:",
            "        self._running = False",
            "        self.log.info('Stopping.')",
            "",
            "    def process(self, request: dict) -> Result:",
            "        action = request.get('action', '')",
            "        if action == 'read':",
            "            content = self.files.read(request.get('file', ''))",
            "            return Result(content is not None, content, '' if content else 'Not found')",
            "        if action == 'write':",
            "            self.files.write(request.get('file', 'out.txt'), request.get('content', ''))",
            "            return Result(True, None)",
            "        return Result(False, error=f'Unknown action: {action}')",
            "",
            "def main() -> int:",
            "    config = Config()",
            "    if '--debug' in sys.argv:",
            "        config.debug = True",
            "        config.log_level = 'DEBUG'",
            "    app = App(config)",
            "    app.start()",
            "    app.log.info('App ready.')",
            "    app.stop()",
            "    return 0",
            "",
            "if __name__ == '__main__':",
            "    sys.exit(main())",
        },
        Enumerable.Empty<string>()
    ));

    private static readonly TestDefinition LargeTest = new(
        TestIdLarge,
        "FileWrite Large (~150-line app)",
        $"Use write_file to create a file called 'app.py' with exactly this content:\n\n{LargeContent}\n\nWrite the file now.",
        "app.py",
        LargeContent
    );

    // ── Run ───────────────────────────────────────────────────────────────────

    /// <summary>
    /// Run one capability test against the given model.
    /// Uses a temporary workspace that is cleaned up after the test.
    /// </summary>
    public static async Task<ModelCapabilityTestResult> RunAsync(
        string modelId,
        string testId,
        string ollamaHost,
        IProgress<string>? progress = null,
        CancellationToken ct = default)
    {
        var test = testId switch
        {
            "FileWriteSmall"  => SmallTest,
            "FileWriteMedium" => MediumTest,
            "FileWriteLarge"  => LargeTest,
            _ => throw new ArgumentException($"Unknown test ID: {testId}"),
        };

        var tempDir = Path.Combine(
            Path.GetTempPath(), "TheOrc", "ModelTests",
            DateTime.Now.ToString("yyyyMMdd_HHmmss") + "_" + modelId.Replace(":", "_").Replace("/", "_"));

        Directory.CreateDirectory(tempDir);
        progress?.Report($"Temp workspace: {tempDir}");

        var result = new ModelCapabilityTestResult
        {
            ModelId   = modelId,
            TestId    = testId,
            TestName  = test.TestName,
            Timestamp = DateTime.UtcNow,
            ExpectedFile = test.ExpectedFileName,
        };

        try
        {
            progress?.Report($"[PHASE:sending] Sending prompt to {modelId}…");
            var sw = System.Diagnostics.Stopwatch.StartNew();
            var rawResponse = await CallOllamaAsync(ollamaHost, modelId, test.PromptText, ct);
            sw.Stop();
            progress?.Report($"[PHASE:received:{rawResponse.Length}] Response received — {rawResponse.Length:N0} chars in {sw.Elapsed.TotalSeconds:F1}s.");

            // Analyse the raw response JSON for write_file tool calls
            progress?.Report("[PHASE:analyzing] Analyzing response…");
            AnalyseResponse(rawResponse, test, tempDir, result, progress);

            // Try to write the file if we found valid content
            if (result.ValidJson && !string.IsNullOrEmpty(_lastExtractedContent))
            {
                var filePath = Path.Combine(tempDir, test.ExpectedFileName);
                await File.WriteAllTextAsync(filePath, _lastExtractedContent, ct);
                result.FileWritten      = File.Exists(filePath);
                result.ActualFileSizeBytes = result.FileWritten
                    ? (int)new FileInfo(filePath).Length : 0;
                progress?.Report(result.FileWritten
                    ? $"✅ File written: {test.ExpectedFileName} ({result.ActualFileSizeBytes} bytes)"
                    : "❌ File not written.");
            }

            // Determine overall result
            result.Result = result.ValidJson && result.FileWritten ? "pass"
                          : result.ValidJson && !result.FileWritten ? "partial"
                          : "fail";

            progress?.Report($"[RESULT:{result.Result}] {result.Result.ToUpperInvariant()}");
        }
        catch (OperationCanceledException) { result.Result = "fail"; result.Notes = "Cancelled."; }
        catch (Exception ex)               { result.Result = "fail"; result.Notes = $"Error: {ex.Message}"; }
        finally
        {
            // Best-effort cleanup of temp dir
            try { Directory.Delete(tempDir, true); } catch { /* non-fatal */ }
        }

        await ModelWikiService.SaveUserResultAsync(result);
        return result;
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    [ThreadStatic] private static string? _lastExtractedContent;

    private static async Task<string> CallOllamaAsync(
        string host, string modelId, string prompt, CancellationToken ct)
    {
        var writeFileTool = JsonNode.Parse("""
            {
              "type": "function",
              "function": {
                "name": "write_file",
                "description": "Write content to a file at the given path",
                "parameters": {
                  "type": "object",
                  "properties": {
                    "path":    { "type": "string", "description": "File path to write" },
                    "content": { "type": "string", "description": "File content"       }
                  },
                  "required": ["path", "content"]
                }
              }
            }
            """)!;

        var request = new JsonObject
        {
            ["model"]    = modelId,
            ["stream"]   = false,
            ["messages"] = new JsonArray
            {
                new JsonObject
                {
                    ["role"]    = "user",
                    ["content"] = prompt,
                }
            },
            ["tools"] = new JsonArray { writeFileTool },
        };

        var url     = $"{host.TrimEnd('/')}/v1/chat/completions";
        var content = new StringContent(request.ToJsonString(),
            Encoding.UTF8, "application/json");

        var resp = await _http.PostAsync(url, content, ct);
        resp.EnsureSuccessStatusCode();
        return await resp.Content.ReadAsStringAsync(ct);
    }

    private static void AnalyseResponse(
        string rawResponse,
        TestDefinition test,
        string tempDir,
        ModelCapabilityTestResult result,
        IProgress<string>? progress)
    {
        _lastExtractedContent = null;

        try
        {
            var doc = JsonDocument.Parse(rawResponse);
            var root = doc.RootElement;

            // Try native tool_calls first
            if (root.TryGetProperty("choices", out var choices) &&
                choices.GetArrayLength() > 0)
            {
                var choice  = choices[0];
                var message = choice.GetProperty("message");

                if (message.TryGetProperty("tool_calls", out var toolCalls) &&
                    toolCalls.GetArrayLength() > 0)
                {
                    var tc   = toolCalls[0];
                    var func = tc.GetProperty("function");
                    var name = func.GetProperty("name").GetString();

                    if (name == "write_file")
                    {
                        var argsRaw = func.GetProperty("arguments").GetString() ?? "{}";
                        var opens   = argsRaw.Count(c => c == '{');
                        var closes  = argsRaw.Count(c => c == '}');
                        result.OpenBraceCount  = opens;
                        result.CloseBraceCount = closes;
                        result.Truncated       = opens > closes;

                        if (!result.Truncated)
                        {
                            var args    = JsonDocument.Parse(argsRaw).RootElement;
                            var content = args.TryGetProperty("content", out var cv)
                                        ? cv.GetString() : null;
                            result.ValidJson = true;
                            _lastExtractedContent = content;
                            progress?.Report($"Native tool call found. JSON valid. Content length: {content?.Length ?? 0}");
                        }
                        else
                        {
                            progress?.Report($"Native tool call found but JSON TRUNCATED (opens={opens} closes={closes}).");
                            result.ValidJson = false;
                            result.Notes = $"write_file JSON truncated at {argsRaw.Length} chars (opens={opens}, closes={closes})";
                        }
                        return;
                    }
                }

                // Try text response containing JSON tool call (text-JSON format)
                if (message.TryGetProperty("content", out var textContent))
                {
                    var text   = textContent.GetString() ?? "";
                    var opens  = text.Count(c => c == '{');
                    var closes = text.Count(c => c == '}');
                    result.OpenBraceCount  = opens;
                    result.CloseBraceCount = closes;
                    progress?.Report($"Text response ({text.Length} chars, opens={opens} closes={closes}).");

                    // Look for write_file JSON block in text
                    var nameIdx = text.IndexOf("\"write_file\"", StringComparison.OrdinalIgnoreCase);
                    if (nameIdx >= 0 || text.Contains("write_file"))
                    {
                        result.Truncated = opens > closes;
                        if (!result.Truncated && opens > 0)
                        {
                            // Try to extract content field
                            var contentMatch = System.Text.RegularExpressions.Regex.Match(
                                text, @"""content""\s*:\s*""((?:[^""\\]|\\.)*)""");
                            if (contentMatch.Success)
                            {
                                _lastExtractedContent = contentMatch.Groups[1].Value
                                    .Replace("\\n", "\n").Replace("\\\"", "\"").Replace("\\\\", "\\");
                                result.ValidJson = true;
                                progress?.Report($"Text-JSON write_file found. Content length: {_lastExtractedContent.Length}");
                            }
                        }
                        else if (result.Truncated)
                        {
                            result.Notes = $"Text-JSON write_file truncated ({text.Length} chars, opens={opens}, closes={closes})";
                        }
                    }
                    else if (text.Length == 0)
                    {
                        result.Notes = "Empty response from model.";
                    }
                    else
                    {
                        result.Notes = $"No write_file call found in response ({text.Length} chars).";
                    }
                }
            }
        }
        catch (JsonException ex)
        {
            result.Notes = $"Failed to parse Ollama response: {ex.Message}";
        }
    }
}
