using System.Diagnostics;
using NUnit.Framework;
using OrchestratorIDE.Services.Swarm;

namespace OrchestratorIDE.UITests.Tests;

/// <summary>
/// T16 — Worktree-per-task isolation Phase 1 pure-logic tests.
/// No FlaUI, no Ollama, no network. Uses temporary directories and a real
/// local git binary for worktree operations (git must be in PATH).
/// </summary>
[TestFixture]
public class T16_WorktreeIsolationTests
{
    // ── FileOwnershipLedger ──────────────────────────────────────────────────

    [Test]
    public void FileOwnershipLedger_TwoTasksSameFile_SecondIsRejected()
    {
        var ledger = new FileOwnershipLedger();

        var c1 = ledger.TryClaim("task-A", ["src/Foo.cs"]);
        var c2 = ledger.TryClaim("task-B", ["src/Foo.cs"]);

        Assert.That(c1, Is.Empty,          "First claim should always succeed.");
        Assert.That(c2, Has.Count.EqualTo(1), "Second claim on same file should conflict.");
        Assert.That(c2[0].Path,        Is.EqualTo("src/foo.cs")); // normalized
        Assert.That(c2[0].OwnedBy,    Is.EqualTo("task-A"));
        Assert.That(c2[0].RequestedBy, Is.EqualTo("task-B"));
    }

    [Test]
    public void FileOwnershipLedger_ReleaseUnblocksSuccessor()
    {
        var ledger = new FileOwnershipLedger();
        ledger.TryClaim("task-A", ["src/Foo.cs"]);

        ledger.Release("task-A");

        var c = ledger.TryClaim("task-B", ["src/Foo.cs"]);
        Assert.That(c, Is.Empty, "After Release, successor should claim cleanly.");
        Assert.That(ledger.OwnerOf("src/Foo.cs"), Is.EqualTo("task-B"));
    }

    [Test]
    public void FileOwnershipLedger_PathNormalization_CaseAndSeparators()
    {
        var ledger = new FileOwnershipLedger();
        ledger.TryClaim("task-A", ["src/Foo.cs"]);

        Assert.That(ledger.OwnerOf("src/Foo.cs"),   Is.EqualTo("task-A"), "exact");
        Assert.That(ledger.OwnerOf("SRC/FOO.CS"),   Is.EqualTo("task-A"), "upper-case");
        Assert.That(ledger.OwnerOf(@"src\Foo.cs"),  Is.EqualTo("task-A"), "backslash");
        Assert.That(ledger.OwnerOf("/src/Foo.cs"),  Is.EqualTo("task-A"), "leading slash");
        Assert.That(ledger.OwnerOf("src/Bar.cs"),   Is.Null,              "different file");
    }

    // ── WorktreeManager — Greenfield mode ────────────────────────────────────

    [Test]
    public void WorktreeManager_GreenfieldMode_InitsScratchRepo()
    {
        var runDir = CreateTempDir("run");
        try
        {
            var wm = new WorktreeManager(runDir, workspaceRoot: null);
            Assert.That(wm.RepoMode, Is.False, "No workspace root → greenfield.");

            var handle = wm.Acquire("t1", "Coder");
            Assert.That(Directory.Exists(handle.Path), Is.True, "Task dir should be created.");
            Assert.That(handle.Branch, Is.Null, "Greenfield has no branch.");

            File.WriteAllText(Path.Combine(handle.Path, "output.cs"), "// generated by task t1");

            var result = wm.Merge(handle, ["output.cs"]);

            Assert.Multiple(() =>
            {
                Assert.That(result.FilesMerged, Is.EqualTo(1));
                Assert.That(result.Files, Has.Member("output.cs"));

                var integrationFile = Path.Combine(runDir, "integration", "output.cs");
                Assert.That(File.Exists(integrationFile), Is.True, "File should land in integration dir.");

                // Integration dir should be a scratch git repo
                var gitDir = Path.Combine(runDir, "integration", ".git");
                Assert.That(Directory.Exists(gitDir), Is.True, "Scratch git repo should be initialised.");
            });
        }
        finally { TryDelete(runDir); }
    }

    [Test]
    public void WorktreeManager_Merge_DisjointOwnership_NoConflict()
    {
        var runDir = CreateTempDir("run");
        try
        {
            var wm     = new WorktreeManager(runDir, workspaceRoot: null);
            var handle = wm.Acquire("t1", "Coder");

            File.WriteAllText(Path.Combine(handle.Path, "services.cs"), "// service layer");
            File.WriteAllText(Path.Combine(handle.Path, "models.cs"),   "// domain models");

            var ledger = new FileOwnershipLedger();
            ledger.TryClaim("t1", ["services.cs", "models.cs"]);

            var result = wm.Merge(handle, ["services.cs", "models.cs"], ledger);

            Assert.That(result.FilesMerged, Is.EqualTo(2));
            Assert.That(result.Files, Has.Member("services.cs"));
            Assert.That(result.Files, Has.Member("models.cs"));
        }
        finally { TryDelete(runDir); }
    }

    [Test]
    public void WorktreeManager_Merge_UndeclaredOwnedFile_Throws()
    {
        var runDir = CreateTempDir("run");
        try
        {
            // Another task already owns "shared.cs"
            var ledger = new FileOwnershipLedger();
            ledger.TryClaim("other-task", ["shared.cs"]);

            var wm     = new WorktreeManager(runDir, workspaceRoot: null);
            var handle = wm.Acquire("task-a", "Coder");

            File.WriteAllText(Path.Combine(handle.Path, "mine.cs"),   "// mine");
            File.WriteAllText(Path.Combine(handle.Path, "shared.cs"), "// conflict!");

            // task-a declares only "mine.cs" but touches "shared.cs" too
            var ex = Assert.Throws<WorktreeConflictException>(
                () => wm.Merge(handle, ["mine.cs"], ledger));

            Assert.That(ex!.ConflictPath, Is.EqualTo("shared.cs"));
            Assert.That(ex.Claimant,     Is.EqualTo("task-a"));
            Assert.That(ex.Owner,        Is.EqualTo("other-task"));
        }
        finally { TryDelete(runDir); }
    }

    [Test]
    public void WorktreeManager_ReapStale_RemovesOldAbandonedTrees()
    {
        var runDir = CreateTempDir("run");
        try
        {
            var wm = new WorktreeManager(runDir, workspaceRoot: null);

            // Simulate an abandoned task directory
            var abandonedTree = Path.Combine(runDir, "trees", "Coder-abandoned");
            Directory.CreateDirectory(abandonedTree);
            // Backdate it so it looks 2 hours old
            Directory.SetLastWriteTimeUtc(abandonedTree, DateTime.UtcNow.AddHours(-2));

            // A recent tree (should NOT be reaped)
            var activeTree = Path.Combine(runDir, "trees", "Coder-active");
            Directory.CreateDirectory(activeTree);

            var reaped = wm.ReapStale(TimeSpan.FromHours(1));

            Assert.That(reaped, Is.EqualTo(1), "Only the stale tree should be reaped.");
            Assert.That(Directory.Exists(abandonedTree), Is.False, "Stale tree removed.");
            Assert.That(Directory.Exists(activeTree),    Is.True,  "Active tree kept.");
        }
        finally { TryDelete(runDir); }
    }

    // ── WorktreeManager — Repo mode ──────────────────────────────────────────

    [Test]
    [Category("RequiresGit")]
    public void WorktreeManager_RepoMode_AcquireCreatesBranch()
    {
        var repoDir = CreateTempRepo();
        var runDir  = CreateTempDir("run");
        try
        {
            var wm = new WorktreeManager(runDir, repoDir);
            Assert.That(wm.RepoMode, Is.True, "Valid git repo → repo mode.");

            var handle = wm.Acquire("t1", "Coder");

            Assert.That(Directory.Exists(handle.Path), Is.True, "Task worktree should exist.");
            Assert.That(handle.Branch, Does.StartWith("orc/run-"), "Branch should follow orc/ convention.");

            // The integration branch should also exist
            var branches = RunGitCapture(repoDir, "branch --list orc/*");
            Assert.That(branches, Does.Contain("orc/run-"),
                "Both integration and task branches should be created.");
        }
        finally { TryDelete(runDir); TryDelete(repoDir); }
    }

    // ── Scheduler-level: conflict detection is the building block ────────────

    [Test]
    public void Scheduler_DeclaredCollision_LedgerReturnsConflict()
    {
        // This exercises the primitive that Phase 2 scheduler uses to
        // sequence tasks instead of dispatching them in parallel.
        var ledger = new FileOwnershipLedger();

        var c1 = ledger.TryClaim("task-A", ["src/Api.cs", "src/Models.cs"]);
        Assert.That(c1, Is.Empty, "First claim should always succeed.");

        // Task B wants the same Api.cs — conflict on that file
        var c2 = ledger.TryClaim("task-B", ["src/Api.cs", "src/Tests.cs"]);

        Assert.That(c2, Has.Count.EqualTo(1), "Conflict on Api.cs should be returned.");
        Assert.That(c2[0].Path,        Is.EqualTo("src/api.cs")); // normalized
        Assert.That(c2[0].OwnedBy,    Is.EqualTo("task-A"));
        Assert.That(c2[0].RequestedBy, Is.EqualTo("task-B"));

        // Non-conflicting file (Tests.cs) is still claimed by task-B
        Assert.That(ledger.OwnerOf("src/Tests.cs"), Is.EqualTo("task-B"),
            "Non-conflicting files in the same TryClaim call should still be owned.");

        // Snapshot shows complete state
        var snapshot = ledger.Snapshot();
        Assert.That(snapshot.Count, Is.EqualTo(3),
            "Ledger should hold Api.cs (A), Models.cs (A), Tests.cs (B).");
    }

    // ── fixtures and helpers ─────────────────────────────────────────────────

    private static string CreateTempDir(string prefix = "tmp")
    {
        var dir = Path.Combine(Path.GetTempPath(), $"orc_{prefix}_{Guid.NewGuid():N}");
        Directory.CreateDirectory(dir);
        return dir;
    }

    /// <summary>Init a minimal git repo with one commit so HEAD exists.</summary>
    private static string CreateTempRepo()
    {
        var dir = CreateTempDir("repo");
        Git(dir, "init");
        Git(dir, "config user.email test@orc.local");
        Git(dir, "config user.name  TheOrcTest");
        File.WriteAllText(Path.Combine(dir, "README.md"), "# test repo");
        Git(dir, "add .");
        Git(dir, "commit -m init");
        return dir;
    }

    private static void TryDelete(string dir)
    {
        try { Directory.Delete(dir, recursive: true); }
        catch { /* best-effort cleanup */ }
    }

    private static void Git(string dir, string args)
    {
        using var p = Process.Start(new ProcessStartInfo
        {
            FileName               = "git",
            Arguments              = args,
            WorkingDirectory       = dir,
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            UseShellExecute        = false,
            CreateNoWindow         = true,
        }) ?? throw new InvalidOperationException("git not found in PATH");

        var err = p.StandardError.ReadToEnd();
        p.WaitForExit();
        if (p.ExitCode != 0)
            throw new InvalidOperationException($"git {args} failed: {err.Trim()}");
    }

    private static string RunGitCapture(string dir, string args)
    {
        using var p = Process.Start(new ProcessStartInfo
        {
            FileName               = "git",
            Arguments              = args,
            WorkingDirectory       = dir,
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            UseShellExecute        = false,
            CreateNoWindow         = true,
        }) ?? throw new InvalidOperationException("git not found in PATH");

        var output = p.StandardOutput.ReadToEnd();
        p.WaitForExit();
        return output;
    }
}
